=== JohnCoker/thrustcurve3/public/2015/getrockets-response.xsd
<?xml version="1.0" encoding="ASCII"?>
<xs:schema version="2015.1"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.thrustcurve.org/2015/GetRocketsResponse"
 xmlns="http://www.thrustcurve.org/2015/GetRocketsResponse"
 elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      This schema defines the response sent to the ThrustCurve.org get rockets XML API.
      For more information, see the documentation at http://www.thrustcurve.org/searchapi.shtml
    </xs:documentation>
  </xs:annotation>

  <xs:element name="getrockets-response">
    <xs:complexType>
      <xs:sequence>

        <!-- the list of rockets is always present, but may be empty -->
	<xs:element name="results">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rocket" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="id" type="xs:integer" />
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="body-diameter-m" type="xs:decimal" />
                    <xs:element name="mmt-diameter-mm" type="xs:decimal" />
                    <xs:element name="mmt-length-mm" type="xs:decimal" />
                    <xs:element name="weight-kg" type="xs:decimal" />
                    <xs:element name="cd" type="xs:decimal" />
                    <xs:element name="guide-length-m" type="xs:decimal" />
                    <xs:element name="website" type="xs:string" />
                    <xs:element name="comments" type="xs:string" />
                    <xs:element name="created-on" type="xs:date" />
                    <xs:element name="updated-on" type="xs:date" />
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

        <!-- if a general error occurred more detail is returned -->
	<xs:element name="error" type="xs:string" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JohnCoker/thrustcurve3/spec/api/expected/getrockets-POST-others-legacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<getrockets-response xmlns="http://www.thrustcurve.org/2015/GetRocketsResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2015/GetRocketsResponse http://www.thrustcurve.org/2015/getrockets-response.xsd">
    <results>
        <rocket>
            <id>100000x</id>
            <name>Alpha III</name>
            <body-diameter-m>0.024891999999999997</body-diameter-m>
            <mmt-diameter-mm>18</mmt-diameter-mm>
            <mmt-length-mm>76.2</mmt-length-mm>
            <weight-kg>0.0340194</weight-kg>
            <cd>0.4</cd>
            <guide-length-m>0.9144000000000001</guide-length-m>
            <website>https://estesrockets.com/product/001256-alpha-iii/</website>
            <comments>This is my first rocket; I'm very proud!</comments>
            <created-on>2020-09-27</created-on>
            <updated-on>2020-09-27</updated-on>
        </rocket>
        <rocket>
            <id>100000x</id>
            <name>Versatile</name>
            <body-diameter-m>0.033782</body-diameter-m>
            <mmt-diameter-mm>24</mmt-diameter-mm>
            <mmt-length-mm>152.4</mmt-length-mm>
            <weight-kg>0.0850485</weight-kg>
            <cd>0.45</cd>
            <guide-length-m>0.9144000000000001</guide-length-m>
            <comments>Can adapt down to 18mm</comments>
            <created-on>2020-09-27</created-on>
            <updated-on>2020-09-27</updated-on>
        </rocket>
    </results>
</getrockets-response>

=== JohnCoker/thrustcurve3/spec/api/expected/getrockets-POST-mine.xml
<?xml version="1.0" encoding="UTF-8"?>
<getrockets-response xmlns="http://www.thrustcurve.org/2020/GetRocketsResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2020/GetRocketsResponse http://www.thrustcurve.org/2020/getrockets-response.xsd">
    <results>
        <rocket>
            <id>5f70ff46e645437e11edd06b</id>
            <name>Alpha III</name>
            <public>true</public>
            <body-diameter-m>0.024891999999999997</body-diameter-m>
            <mmt-diameter-mm>18</mmt-diameter-mm>
            <mmt-length-mm>76.2</mmt-length-mm>
            <mmt-count>1</mmt-count>
            <weight-kg>0.0340194</weight-kg>
            <cd>0.4</cd>
            <guide-length-m>0.9144000000000001</guide-length-m>
            <website>https://estesrockets.com/product/001256-alpha-iii/</website>
            <comments>This is my first rocket; I'm very proud!</comments>
            <created-on>2020-09-27</created-on>
            <updated-on>2020-09-27</updated-on>
        </rocket>
        <rocket>
            <id>5f70fff1e645437e11edd06c</id>
            <name>Secret Project</name>
            <public>false</public>
            <body-diameter-m>0.06604</body-diameter-m>
            <mmt-diameter-mm>24</mmt-diameter-mm>
            <mmt-length-mm>101.6</mmt-length-mm>
            <mmt-count>3</mmt-count>
            <weight-kg>0.1417475</weight-kg>
            <cd>0.5</cd>
            <guide-length-m>1.2192</guide-length-m>
            <comments>Don't tell anyone (yet).</comments>
            <created-on>2020-09-27</created-on>
            <updated-on>2020-09-27</updated-on>
        </rocket>
        <rocket>
            <id>5f711cc28a854d83fee8efd9</id>
            <name>Versatile</name>
            <public>true</public>
            <body-diameter-m>0.033782</body-diameter-m>
            <mmt-diameter-mm>24</mmt-diameter-mm>
            <mmt-length-mm>152.4</mmt-length-mm>
            <mmt-count>1</mmt-count>
            <weight-kg>0.0850485</weight-kg>
            <adapters>
                <adapter>
                    <mmt-diameter-mm>18</mmt-diameter-mm>
                    <mmt-length-mm>76.2</mmt-length-mm>
                    <weight-kg>0.01417475</weight-kg>
                </adapter>
            </adapters>
            <cd>0.45</cd>
            <guide-length-m>0.9144000000000001</guide-length-m>
            <comments>Can adapt down to 18mm</comments>
            <created-on>2020-09-27</created-on>
            <updated-on>2020-09-27</updated-on>
        </rocket>
    </results>
</getrockets-response>
