=== JohnCoker/thrustcurve3/public/2014/motorguide-response.xsd
<?xml version="1.0" encoding="ASCII"?>
<?xml-stylesheet type="text/xsl" href="/xs3p.xsl"?>
<xs:schema version="2014.1"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.thrustcurve.org/2014/MotorGuideResponse"
 xmlns="http://www.thrustcurve.org/2014/MotorGuideResponse"
 elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      This schema defines the response returned by the ThrustCurve.org motor guide XML API.
      For more information, see the documentation at http://www.thrustcurve.org/searchapi.shtml
    </xs:documentation>
  </xs:annotation>

  <xs:element name="motorguide-response">
    <xs:complexType>
      <xs:sequence>

        <!-- the search criteria are returned, along with the number of matches -->
	<xs:element name="criteria">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="criterion" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="value" type="xs:string"/>
                    <xs:element name="matches" type="xs:integer"/>
                    <xs:element name="error" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
	      </xs:element>
              <xs:element name="matches" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

        <!-- the list of results is always present, but may be empty -->
	<xs:element name="results">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="result" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <!-- status, always present -->
                    <xs:element name="status">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="ok"/>
                          <xs:enumeration value="dimensions"/>
                          <xs:enumeration value="5-to-1"/>
                          <xs:enumeration value="guide-vel"/>
                          <xs:enumeration value="too-low"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <!-- motor info, always present -->
                    <xs:element name="motor-id" type="xs:integer"/>
	            <xs:element name="manufacturer" type="xs:string"/>
	            <xs:element name="manufacturer-abbrev" type="xs:string"/>
	            <xs:element name="designation" type="xs:string"/>
	            <xs:element name="common-name" type="xs:string"/>
                    <xs:element name="thrust-to-weight" type="xs:decimal"/>
                    <xs:element name="simulations-run" type="xs:integer"/>

                    <!-- simulation results, present if simulations-run > 0 -->
                    <xs:element name="liftoff-mass" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="burnout-mass" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="liftoff-time" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="burnout-time" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="apogee-time" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="max-acceleration" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="guide-velocity" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="max-velocity" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="burnout-altitude" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="max-altitude" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="optimal-delay" type="xs:decimal" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
	      </xs:element>
            </xs:sequence>
            <xs:attribute name="ok-count" type="xs:integer"/>
            <xs:attribute name="failed-count" type="xs:integer"/>
          </xs:complexType>
	</xs:element>

        <!-- if a general error occurred more detail is returned -->
	<xs:element name="error" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JohnCoker/thrustcurve3/spec/api/expected/motorguide-unmatched-mmt-legacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<motorguide-response xmlns="http://www.thrustcurve.org/2014/MotorGuideResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2014/MotorGuideResponse http://www.thrustcurve.org/2014/motorguide-response.xsd">
    <criteria>
        <criterion>
            <name>impulseClass</name>
            <value>D</value>
            <matches>10</matches>
        </criterion>
        <matches>10</matches>
    </criteria>
    <results ok-count="0" failed-count="0"/>
</motorguide-response>

=== JohnCoker/thrustcurve3/spec/api/expected/motorguide-no-criteria-legacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<motorguide-response xmlns="http://www.thrustcurve.org/2014/MotorGuideResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2014/MotorGuideResponse http://www.thrustcurve.org/2014/motorguide-response.xsd">
    <criteria>
        <matches>280</matches>
    </criteria>
    <results ok-count="5" failed-count="7">
        <result>
            <status>ok</status>
            <motor-id>20</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>C5</designation>
            <common-name>C5</common-name>
            <thrust-to-weight>4.984858067159761</thrust-to-weight>
            <simulations-run>1</simulations-run>
            <liftoff-time>0.03</liftoff-time>
            <burnout-time>1.73</burnout-time>
            <apogee-time>7.279999999999983</apogee-time>
            <max-acceleration>190.5519096951878</max-acceleration>
            <guide-velocity>15.913868995492022</guide-velocity>
            <max-velocity>61.25736811606941</max-velocity>
            <burnout-altitude>69.199747904822</burnout-altitude>
            <max-altitude>229.35653572550592</max-altitude>
            <optimal-delay>5.549999999999983</optimal-delay>
        </result>
        <result>
            <status>ok</status>
            <motor-id>36</motor-id>
            <manufacturer>AeroTech</manufacturer>
            <manufacturer-abbrev>AeroTech</manufacturer-abbrev>
            <designation>D24T</designation>
            <common-name>D24</common-name>
            <thrust-to-weight>12.872827748447863</thrust-to-weight>
            <simulations-run>1</simulations-run>
            <liftoff-time>0.009000000000000001</liftoff-time>
            <burnout-time>0.9</burnout-time>
            <apogee-time>10.80000000000002</apogee-time>
            <max-acceleration>339.0240956360988</max-acceleration>
            <guide-velocity>23.280520841790448</guide-velocity>
            <max-velocity>147.44221449496052</max-velocity>
            <burnout-altitude>88.56031720292509</burnout-altitude>
            <max-altitude>669.5412682222425</max-altitude>
            <optimal-delay>9.90000000000002</optimal-delay>
        </result>
        <result>
            <status>ok</status>
            <motor-id>739</motor-id>
            <manufacturer>AeroTech</manufacturer>
            <manufacturer-abbrev>AeroTech</manufacturer-abbrev>
            <designation>D10W</designation>
            <common-name>D10</common-name>
            <thrust-to-weight>12.311992869048206</thrust-to-weight>
            <simulations-run>1</simulations-run>
            <liftoff-time>0.01</liftoff-time>
            <burnout-time>1.385</burnout-time>
            <apogee-time>10.890000000000022</apogee-time>
            <max-acceleration>205.96157816548836</max-acceleration>
            <guide-velocity>17.637565084427315</guide-velocity>
            <max-velocity>137.25511162170062</max-velocity>
            <burnout-altitude>130.94129416479478</burnout-altitude>
            <max-altitude>655.1655375118384</max-altitude>
            <optimal-delay>9.505000000000022</optimal-delay>
        </result>
        <result>
            <status>ok</status>
            <motor-id>33</motor-id>
            <manufacturer>AeroTech</manufacturer>
            <manufacturer-abbrev>AeroTech</manufacturer-abbrev>
            <designation>D13W</designation>
            <common-name>D13</common-name>
            <thrust-to-weight>12.35162946312653</thrust-to-weight>
            <simulations-run>1</simulations-run>
            <liftoff-time>0.01</liftoff-time>
            <burnout-time>1.7</burnout-time>
            <apogee-time>11.150000000000025</apogee-time>
            <max-acceleration>202.9084551625239</max-acceleration>
            <guide-velocity>20.225234201325</guide-velocity>
            <max-velocity>146.08959051357414</max-velocity>
            <burnout-altitude>184.72047574736234</burnout-altitude>
            <max-altitude>711.1774670044884</max-altitude>
            <optimal-delay>9.450000000000026</optimal-delay>
        </result>
        <result>
            <status>ok</status>
            <motor-id>35</motor-id>
            <manufacturer>AeroTech</manufacturer>
            <manufacturer-abbrev>AeroTech</manufacturer-abbrev>
            <designation>D21T</designation>
            <common-name>D21</common-name>
            <thrust-to-weight>20.394324259558566</thrust-to-weight>
            <simulations-run>1</simulations-run>
            <liftoff-time>0.009399999999999999</liftoff-time>
            <burnout-time>0.94</burnout-time>
            <apogee-time>11.049400000000022</apogee-time>
            <max-acceleration>292.7761827185242</max-acceleration>
            <guide-velocity>22.564510489810782</guide-velocity>
            <max-velocity>161.258131234474</max-velocity>
            <burnout-altitude>98.27863701274039</burnout-altitude>
            <max-altitude>721.6995745020256</max-altitude>
            <optimal-delay>10.109400000000022</optimal-delay>
        </result>
    </results>
</motorguide-response>

=== JohnCoker/thrustcurve3/spec/api/expected/motorguide-unmatched-criteria.xml
<?xml version="1.0" encoding="UTF-8"?>
<motorguide-response xmlns="http://www.thrustcurve.org/2020/MotorGuideResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2020/MotorGuideResponse http://www.thrustcurve.org/2020/motorguide-response.xsd">
    <criteria>
        <criterion>
            <name>manufacturer</name>
            <value>Kosdon</value>
            <matches>42</matches>
        </criterion>
        <criterion>
            <name>impulseClass</name>
            <value>A</value>
            <matches>6</matches>
        </criterion>
        <matches>0</matches>
    </criteria>
    <results ok-count="0" failed-count="0"/>
</motorguide-response>
