=== JohnCoker/thrustcurve3/public/2011/search-response.xsd
<?xml version="1.0" encoding="ASCII"?>
<xs:schema version="2011.1"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.thrustcurve.org/2011/SearchResponse"
 xmlns="http://www.thrustcurve.org/2011/SearchResponse"
 elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      This schema defines the response returned by the ThrustCurve.org search XML API.
      For more information, see the documentation at http://www.thrustcurve.org/searchapi.shtml
    </xs:documentation>
  </xs:annotation>

  <xs:element name="search-response">
    <xs:complexType>
      <xs:sequence>

        <!-- the search criteria are returned, along with the number of matches -->
	<xs:element name="criteria">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="criterion" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="value" type="xs:string"/>
                    <xs:element name="matches" type="xs:integer"/>
                    <xs:element name="error" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
	      </xs:element>
              <xs:element name="matches" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

        <!-- the list of results is always present, but may be empty -->
	<xs:element name="results">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="result" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="motor-id" type="xs:integer"/>
	            <xs:element name="manufacturer" type="xs:string" minOccurs="0"/>
	            <xs:element name="manufacturer-abbrev" type="xs:string" minOccurs="0"/>
	            <xs:element name="designation" type="xs:string" minOccurs="0"/>
	            <xs:element name="brand-name" type="xs:string" minOccurs="0"/>
	            <xs:element name="common-name" type="xs:string" minOccurs="0"/>
	            <xs:element name="impulse-class" type="xs:string" minOccurs="0"/>
                    <xs:element name="diameter" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="length" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="type" type="xs:string" minOccurs="0"/>
	            <xs:element name="cert-org" type="xs:string" minOccurs="0"/>
                    <xs:element name="avg-thrust-n" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="max-thrust-n" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="tot-impulse-ns" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="burn-time-s" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="data-files" type="xs:integer" minOccurs="0"/>
                    <xs:element name="info-url" type="xs:anyURI" minOccurs="0"/>
                    <xs:element name="total-weight-g" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="prop-weight-g" type="xs:decimal" minOccurs="0"/>
                    <xs:element name="delays" type="xs:string" minOccurs="0"/>
                    <xs:element name="case-info" type="xs:string" minOccurs="0"/>
                    <xs:element name="prop-info" type="xs:string" minOccurs="0"/>
                    <xs:element name="updated-on" type="xs:date" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
	      </xs:element>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

        <!-- if a general error occurred more detail is returned -->
	<xs:element name="error" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JohnCoker/thrustcurve3/spec/api/expected/search-POST-manufacturer.xml
<?xml version="1.0" encoding="UTF-8"?>
<search-response xmlns="http://www.thrustcurve.org/2020/SearchResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2020/SearchResponse http://www.thrustcurve.org/2020/search-response.xsd">
    <criteria>
        <criterion>
            <name>manufacturer</name>
            <value>Estes</value>
            <matches>22</matches>
        </criterion>
        <matches>22</matches>
    </criteria>
    <results>
        <result>
            <motor-id>56a409280002310000000004</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>1/4A3</designation>
            <common-name>1/4A3</common-name>
            <impulse-class>A</impulse-class>
            <diameter>13</diameter>
            <length>45</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>2.36</avg-thrust-n>
            <max-thrust-n>4.95</max-thrust-n>
            <tot-impulse-ns>0.59</tot-impulse-ns>
            <burn-time-s>0.25</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/qtrA3.pdf</info-url>
            <prop-weight-g>0.83</prop-weight-g>
            <delays>3</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a409280002310000000006</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>1/2A3</designation>
            <common-name>1/2A3</common-name>
            <impulse-class>A</impulse-class>
            <diameter>13</diameter>
            <length>45</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>3.03</avg-thrust-n>
            <max-thrust-n>7.62</max-thrust-n>
            <tot-impulse-ns>1.09</tot-impulse-ns>
            <burn-time-s>0.36</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/halfA3T.pdf</info-url>
            <prop-weight-g>2</prop-weight-g>
            <delays>2,4</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a409280002310000000007</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>1/2A6</designation>
            <common-name>1/2A6</common-name>
            <impulse-class>A</impulse-class>
            <diameter>18</diameter>
            <length>70</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>3.42</avg-thrust-n>
            <max-thrust-n>7.86</max-thrust-n>
            <tot-impulse-ns>1.13</tot-impulse-ns>
            <burn-time-s>0.33</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/halfA6.pdf</info-url>
            <prop-weight-g>2.6</prop-weight-g>
            <delays>2</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a40928000231000000000c</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>A10</designation>
            <common-name>A10</common-name>
            <impulse-class>A</impulse-class>
            <diameter>13</diameter>
            <length>45</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>2.35</avg-thrust-n>
            <max-thrust-n>12.64</max-thrust-n>
            <tot-impulse-ns>2</tot-impulse-ns>
            <burn-time-s>0.85</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/A10T.pdf</info-url>
            <prop-weight-g>3.8</prop-weight-g>
            <delays>0,3,P</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a409280002310000000009</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>A3</designation>
            <common-name>A3</common-name>
            <impulse-class>A</impulse-class>
            <diameter>13</diameter>
            <length>45</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>2.2</avg-thrust-n>
            <max-thrust-n>5.83</max-thrust-n>
            <tot-impulse-ns>2.22</tot-impulse-ns>
            <burn-time-s>1.01</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/A3T.pdf</info-url>
            <prop-weight-g>3.3</prop-weight-g>
            <delays>4</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a40928000231000000000b</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>A8</designation>
            <common-name>A8</common-name>
            <impulse-class>A</impulse-class>
            <diameter>18</diameter>
            <length>70</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>3.18</avg-thrust-n>
            <max-thrust-n>9.73</max-thrust-n>
            <tot-impulse-ns>2.32</tot-impulse-ns>
            <burn-time-s>0.73</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/A8.pdf</info-url>
            <prop-weight-g>3.3</prop-weight-g>
            <delays>0,3,5</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a40928000231000000000e</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>B4</designation>
            <common-name>B4</common-name>
            <impulse-class>B</impulse-class>
            <diameter>18</diameter>
            <length>70</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>4.17</avg-thrust-n>
            <max-thrust-n>12.75</max-thrust-n>
            <tot-impulse-ns>4.29</tot-impulse-ns>
            <burn-time-s>1.03</burn-time-s>
            <data-files>3</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/B4.pdf</info-url>
            <prop-weight-g>6</prop-weight-g>
            <delays>2,4</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a409280002310000000010</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>B6</designation>
            <common-name>B6</common-name>
            <impulse-class>B</impulse-class>
            <diameter>18</diameter>
            <length>70</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>5.03</avg-thrust-n>
            <max-thrust-n>12.14</max-thrust-n>
            <tot-impulse-ns>4.33</tot-impulse-ns>
            <burn-time-s>0.86</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://www.nar.org/SandT/pdf/Estes/B6.pdf</info-url>
            <total-weight-g>15</total-weight-g>
            <prop-weight-g>5.6</prop-weight-g>
            <delays>0,2,4,6</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a40928000231000000001a</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>C11</designation>
            <common-name>C11</common-name>
            <impulse-class>C</impulse-class>
            <diameter>24</diameter>
            <length>70</length>
            <type>SU</type>
            <cert-org>National Association of Rocketry</cert-org>
            <avg-thrust-n>10.86</avg-thrust-n>
            <max-thrust-n>21.73</max-thrust-n>
            <tot-impulse-ns>8.8</tot-impulse-ns>
            <burn-time-s>0.81</burn-time-s>
            <data-files>2</data-files>
            <info-url>http://nar.org/SandT/pdf/Estes/C11.pdf</info-url>
            <prop-weight-g>12</prop-weight-g>
            <delays>0,3,5,7</delays>
            <prop-info>black powder</prop-info>
            <sparky>false</sparky>
            <updated-on>2014-07-05</updated-on>
        </result>
        <result>
            <motor-id>56a409280002310000000015</motor-id>
            <manufacturer>Estes Industries</manufacturer>
            <manufacturer-abbrev>Estes</manufacturer-abbrev>
            <designation>C6</designation>
            <common-name>C6</common-name>
