=== JohnCoker/thrustcurve3/public/2008/metadata-response.xsd
<?xml version="1.0"?>
<xs:schema version="2008.1"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.thrustcurve.org/2008/MetadataResponse"
 xmlns="http://www.thrustcurve.org/2008/MetadataResponse"
 elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation xml:lang="en">
      This schema defines the response returned by the ThrustCurve.org metadata XML API.
      For more information, see the documentation at http://www.thrustcurve.org/searchapi.shtml
    </xs:documentation>
  </xs:annotation>

  <xs:complexType name="NameAndAbbrev">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="abbrev" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="metadata-response">
    <xs:complexType>
      <xs:sequence>
        <!-- each set of results is always present, but may be empty -->
	<xs:element name="manufacturers" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="manufacturer"
                          minOccurs="0" maxOccurs="unbounded"
                          type="NameAndAbbrev"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

	<xs:element name="cert-orgs" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="cert-org"
                          minOccurs="0" maxOccurs="unbounded"
                          type="NameAndAbbrev"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

	<xs:element name="types" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="type"
                          minOccurs="0" maxOccurs="unbounded"
                          type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

	<xs:element name="diameters" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="diameter"
                          minOccurs="0" maxOccurs="unbounded"
                          type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

	<xs:element name="impulse-classes" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
	      <xs:element name="impulse-class"
                          minOccurs="0" maxOccurs="unbounded"
                          type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
	</xs:element>

        <!-- if a general error occurred, more detail is returned -->
	<xs:element name="error" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JohnCoker/thrustcurve3/spec/api/expected/metadata-POST-avail.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata-response xmlns="http://www.thrustcurve.org/2008/MetadataResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.thrustcurve.org/2008/MetadataResponse http://www.thrustcurve.org/2008/metadata-response.xsd">
    <manufacturers>
        <manufacturer abbrev="AeroTech">AeroTech</manufacturer>
        <manufacturer abbrev="Estes">Estes Industries</manufacturer>
    </manufacturers>
    <cert-orgs>
        <cert-org abbrev="NAR">National Association of Rocketry</cert-org>
        <cert-org abbrev="TRA">Tripoli Rocketry Association, Inc.</cert-org>
    </cert-orgs>
    <types>
        <type>SU</type>
        <type>reload</type>
    </types>
    <diameters>
        <diameter>13</diameter>
        <diameter>18</diameter>
        <diameter>24</diameter>
        <diameter>29</diameter>
        <diameter>32</diameter>
        <diameter>38</diameter>
        <diameter>54</diameter>
        <diameter>75</diameter>
        <diameter>98</diameter>
    </diameters>
    <impulse-classes>
        <impulse-class>A</impulse-class>
        <impulse-class>B</impulse-class>
        <impulse-class>C</impulse-class>
        <impulse-class>D</impulse-class>
        <impulse-class>E</impulse-class>
        <impulse-class>F</impulse-class>
        <impulse-class>G</impulse-class>
        <impulse-class>H</impulse-class>
        <impulse-class>I</impulse-class>
        <impulse-class>J</impulse-class>
        <impulse-class>K</impulse-class>
        <impulse-class>L</impulse-class>
        <impulse-class>M</impulse-class>
        <impulse-class>N</impulse-class>
    </impulse-classes>
</metadata-response>
